name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure output directory exists
        run: mkdir -p output

      - name: Generate Pac-Man graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: samiralam04
          player_style: aggressive

      - name: Move generated files to output folder
        run: |
          mv pacman-contribution-graph.svg output/ 2>/dev/null || true
          mv pacman-contribution-graph-dark.svg output/ 2>/dev/null || true

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pac-man contribution graph"
          branch: main
          file_pattern: 'output/*.svg'
